package com.lotato.pro.utils;

import com.lotato.pro.models.Bet;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class GameEngine {

    public static boolean validateEntry(String type, String num) {
        String cleanNum = num.replace("-", "").replace("&", "");
        switch (type) {
            case "borlette": return cleanNum.length() == 2;
            case "lotto3":   return cleanNum.length() == 3;
            case "lotto4":   return cleanNum.length() == 4;
            case "lotto5":   return cleanNum.length() == 5;
            case "mariage":  return cleanNum.length() == 4;
            case "auto_marriage":
            case "auto_lotto4":
            case "auto_lotto5":
            case "bo":
            case "grap":
                return true;
            default:
                return type.startsWith("n");
        }
    }

    public static String getCleanNumber(String num) {
        return num.replace("-", "").replace("&", "");
    }

    public static List<Bet> generateBOBets(double amount, String drawId, String drawName) {
        List<Bet> bets = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            String num = String.format("%02d", i);
            if (num.charAt(0) == num.charAt(1)) {
                Bet bet = new Bet("borlette", num, num, amount, drawId, drawName);
                bet.setAutoGenerated(true);
                bet.setSpecialType("BO");
                bets.add(bet);
            }
        }
        return bets;
    }

    public static List<Bet> generateGRAPBets(double amount, String drawId, String drawName) {
        List<Bet> bets = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            String num = "" + i + i + i;
            Bet bet = new Bet("lotto3", num, num, amount, drawId, drawName);
            bet.setAutoGenerated(true);
            bet.setSpecialType("GRAP");
            bets.add(bet);
        }
        return bets;
    }

    public static List<Bet> generateNBets(int digit, double amount, String drawId, String drawName) {
        List<Bet> bets = new ArrayList<>();
        for (int i = 0; i < 100; i++) {
            String num = String.format("%02d", i);
            if (num.charAt(1) - '0' == digit) {
                Bet bet = new Bet("borlette", num, num, amount, drawId, drawName);
                bet.setAutoGenerated(true);
                bet.setSpecialType("N" + digit);
                bets.add(bet);
            }
        }
        return bets;
    }

    public static List<Bet> generateAutoMarriageBets(List<Bet> currentCart, double amount, String drawId, String drawName) {
        List<String> borletteNumbers = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        for (Bet b : currentCart) {
            if ("borlette".equals(b.getGame()) && b.getDrawId().equals(drawId)) {
                String clean = b.getCleanNumber();
                if (clean.length() == 2 && seen.add(clean)) {
                    borletteNumbers.add(clean);
                }
            }
        }
        List<Bet> bets = new ArrayList<>();
        for (int i = 0; i < borletteNumbers.size(); i++) {
            for (int j = i + 1; j < borletteNumbers.size(); j++) {
                String n1 = borletteNumbers.get(i);
                String n2 = borletteNumbers.get(j);
                Bet bet = new Bet("auto_marriage", n1 + "&" + n2, n1 + n2, amount, drawId, drawName);
                bet.setAutoGenerated(true);
                bets.add(bet);
            }
        }
        return bets;
    }

    public static List<Bet> generateAutoLotto4Bets(List<Bet> currentCart, double amount, String drawId, String drawName) {
        List<String> borletteNumbers = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        for (Bet b : currentCart) {
            if ("borlette".equals(b.getGame()) && b.getDrawId().equals(drawId)) {
                String clean = b.getCleanNumber();
                if (clean.length() == 2 && seen.add(clean)) borletteNumbers.add(clean);
            }
        }
        List<Bet> bets = new ArrayList<>();
        for (int i = 0; i < borletteNumbers.size(); i++) {
            for (int j = 0; j < borletteNumbers.size(); j++) {
                if (i != j) {
                    String n1 = borletteNumbers.get(i);
                    String n2 = borletteNumbers.get(j);
                    Bet bet = new Bet("auto_lotto4", n1 + "-" + n2, n1 + n2, amount, drawId, drawName);
                    bet.setAutoGenerated(true);
                    bets.add(bet);
                }
            }
        }
        return bets;
    }

    public static List<Bet> generateAutoLotto5Bets(List<Bet> currentCart, double amount, String drawId, String drawName) {
        List<String> lotto3Numbers = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        for (Bet b : currentCart) {
            if ("lotto3".equals(b.getGame()) && b.getDrawId().equals(drawId)) {
                String clean = b.getCleanNumber();
                if (clean.length() == 3 && seen.add(clean)) lotto3Numbers.add(clean);
            }
        }
        List<Bet> bets = new ArrayList<>();
        for (int i = 0; i < lotto3Numbers.size(); i++) {
            for (int j = 0; j < lotto3Numbers.size(); j++) {
                if (i != j) {
                    String n1 = lotto3Numbers.get(i);
                    String n2 = lotto3Numbers.get(j);
                    String last2 = n2.substring(n2.length() - 2);
                    Bet bet = new Bet("auto_lotto5", n1 + "-" + last2, n1 + last2, amount, drawId, drawName);
                    bet.setAutoGenerated(true);
                    bets.add(bet);
                }
            }
        }
        return bets;
    }

    public static List<Bet> generateLottoBetsWithOptions(String gameType, String num, double amount,
                                                          boolean[] options, String drawId, String drawName) {
        List<Bet> bets = new ArrayList<>();
        String cleanNum = getCleanNumber(num);
        for (int i = 0; i < options.length; i++) {
            if (options[i]) {
                String displayNum = cleanNum;
                if ("lotto4".equals(gameType) && cleanNum.length() == 4) {
                    displayNum = cleanNum.substring(0, 2) + "-" + cleanNum.substring(2, 4);
                } else if ("lotto5".equals(gameType) && cleanNum.length() == 5) {
                    displayNum = cleanNum.substring(0, 3) + "-" + cleanNum.substring(3, 5);
                }
                Bet bet = new Bet(gameType, displayNum, cleanNum, amount, drawId, drawName);
                bet.setOption(i + 1);
                bets.add(bet);
            }
        }
        return bets;
    }

    public static List<Bet> generateFreeMarriages(List<Bet> cart, String drawId, String drawName,
                                                    int count, double winAmount) {
        List<Bet> freeBets = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            int n1 = (int)(Math.random() * 100);
            int n2 = (int)(Math.random() * 100);
            String s1 = String.format("%02d", n1);
            String s2 = String.format("%02d", n2);
            Bet bet = new Bet("auto_marriage", s1 + "&" + s2, s1 + s2, 0, drawId, drawName);
            bet.setFree(true);
            bet.setFreeType("special_marriage");
            freeBets.add(bet);
        }
        return freeBets;
    }

    public static int countFreeMarriages(double totalAmount, int[][] tiers) {
        for (int[] tier : tiers) {
            int min = tier[0];
            int max = tier[1];
            int count = tier[2];
            if (max == -1 && totalAmount >= min) return count;
            if (max != -1 && totalAmount >= min && totalAmount <= max) return count;
        }
        return 0;
    }

    public static int getMaxLengthForGame(String game) {
        switch (game) {
            case "borlette": return 2;
            case "lotto3": return 3;
            case "lotto4": return 4;
            case "lotto5": return 5;
            case "mariage": return 4;
            default: return 0;
        }
    }
}
